version: '3.5'
services:
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "${PROMETHEUS_PORT_EXTERNAL}:9090"
    labels:
      org.label-schema.group: "monitoring"
  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: ${GRAFANA_CONTAINER_NAME}
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    links:
      - prometheus
    ports:
      - "${GRAFANA_PORT_EXTERNAL}:3000"
    labels:
      org.label-schema.group: "monitoring"
  keycloak:
    image: ${KEYCLOAK_IMAGE}
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: db
      DB_DATABASE: ${POSTGRES_DB}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT_EXTERNAL}:8080
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - ./config/script-init.sql:/docker-entrypoint-initdb.d/script-init.sql
       - postgres_data:/data/postgres
    ports:
      - "${POSTGRES_PORT_EXTERNAL}:5432"
    restart: unless-stopped
  pgadmin:
    image: ${PGADMIN_IMAGE}
    container_name: ${PGADMIN_CONTAINER_NAME}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT_EXTERNAL}:80"
    depends_on:
      - db
    restart: unless-stopped
volumes:
  prometheus_data: {}
  grafana_data: {}
  postgres_data: {}
networks:
  default:
    name: ${NETWORK}
