CREATE TABLE PROPERTIES (
  id SERIAL PRIMARY KEY,
  APPLICATION VARCHAR(25) NOT NULL,
  PROFILE VARCHAR(25) NOT NULL,
  LABEL VARCHAR(25) DEFAULT NULL,
  KEY VARCHAR(255) NOT NULL,
  VALUE VARCHAR(200) NOT NULL
);