name: Build Image Docker FrontEnd
on:
    push:
      branches:
        - 'main'
        - 'releases/**'
        - 'develop'
      paths:
        - 'app-ui/**'
    workflow_dispatch:
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    TAG_IMAGE: ghcr.io/${{ github.repository }}:1.0.1-SNAPSHOT
jobs:
    docker:
        name: Build and Push Image Docker
        environment: dev
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Log in to the Container registry
          uses: docker/login-action@v1
          with:
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: ./app-ui
            push: true
            tags: ${{ env.TAG_IMAGE }}
