version: '3.5'
services:
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "${PROMETHEUS_PORT_EXTERNAL}:9090"
    networks:
      - local-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: ${GRAFANA_CONTAINER_NAME}
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    links:
      - prometheus
    ports:
      - "${GRAFANA_PORT_EXTERNAL}:3000"
    networks:
      - local-net
    labels:
      org.label-schema.group: "monitoring"

volumes:
  prometheus_data: {}
  grafana_data: {}
networks:
  local-net: {}