#application.yml
server:
  port: ${PORT_INTERNAL_CONFIG_SERVER}
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            search-locations:
              - classpath:/profiles # Config files for all microservices
        encrypt:
          enabled: 'true'
  security:
    user:
      name: ${SECURITY-CONFIG-SERVER-USER}
      password: ${SECURITY-CONFIG-SERVER-PASS}
encrypt:
  key: ${SECURITY-CONFIG-SERVER-ENCRYPT}
logging:
  level:
    org:
      springframework:
        security: DEBUG
eureka:
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus