version: '3.5'
services:
  db:
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    networks:
      - local-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - ./script-init.sql:/docker-entrypoint-initdb.d/script-init.sql
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT_EXTERNAL}:5432"
    restart: unless-stopped

  pgadmin:
    image: ${PGADMIN_IMAGE}
    container_name: ${PGADMIN_CONTAINER_NAME}
    networks:
      - local-net
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT_EXTERNAL}:80"
    depends_on:
      - db
    restart: unless-stopped
volumes:
    postgres:
networks:
  local-net: {}