server:
  port: 8087
  servlet:
    context-path: /admin-console
spring:
  security:
    user:
      # Configura o login do servidor.
      name: admin
      password: admin

# LOG
logging:
  level:
    root: info
    web: info
    dev.marksduarte: info
    org.springframework: info
  charset:
    file: utf-8

## SECURITY
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/api/oauth/token
      userAuthorizationUri: http://localhost:8080/api/oauth/authorize
      clientId: client
      clientSecret: secret
    resource:
      jwt:
        keyValue: secret