name: Publish Docker Image Microservices
on:
  push:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TYPE: |-
    ${{
       github.ref_name == 'main' && ''
    || github.ref_name == 'develop'    && 'SNAPSHOT'
    || github.ref_name == 'release'    && 'RELEASE'
    ||                                'snapshot'
    }}
  ENVIRONMENT: |-
    ${{
        github.ref_name == 'main' && 'production'
    || github.ref_name == 'develop'    && 'development'
    || github.ref_name == 'release'    && 'staging'
    ||                                'implementation'
    }}
jobs:
  pre-build:
    name: Prepare Metadata Pipeline
    runs-on: ubuntu-latest
    outputs:
      build_nr: ${{ steps.build_id.outputs.build_nr }}
    steps:
      - name: Extracts value from the build pipeline
        id: build_id
        run: echo "build_nr=${{github.run_number}}-$IMAGE_TYPE" >> $GITHUB_OUTPUT
  compile:
    name: Compile Files Application
    environment: dev
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn -f ./app/app-api/ -B clean package
  build:
    name: Build and Push Docker image 
    runs-on: ubuntu-latest
    permissions: write-all
    environment: $ENVIRONMENT
    needs: [pre-build, compile]
    steps:
      - env:
          OUTPUT1: ${{needs.pre-build.outputs.build_nr}}
        run: echo "$OUTPUT1 $ENVIRONMENT"
    
      - name: Check out the repo
        uses: actions/checkout@v3
            
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ghcr.io/${{ github.repository }}
      
      - name: Config Server Build and Push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./app/app-api/config-server
          push: true
          tags: ${{needs.pre-build.outputs.build_nr}}
          labels: config-server-image-brazona-agile