name: Publish Docker Image Microservices
on:
  push:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ENVIRONMENT: development
jobs:
  pre-build:
    name: Prepare Metadata Pipeline
    runs-on: ubuntu-latest
    outputs:
      build_nr: ${{ steps.build_id.outputs.build_nr }}
      env_name: ${{ steps.env_name.outputs.name }}
    steps:
      - name: Extracts value from the build pipeline
        id: build_id
        run: echo "build_nr=${{github.run_number}}" >> $GITHUB_OUTPUT
      - name: Extracts value from the build pipeline
        id: env_name
        run: |
          if [ $github.head_ref == develop ]
          then
            echo "name=dev" >> $GITHUB_OUTPUT
          if [ $github.head_ref == main ]
          then
            echo "name=production" >> $GITHUB_OUTPUT
          else
            echo "name=dev" >> $GITHUB_OUTPUT
          fi
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: env.ENVIRONMENT
    needs: pre-build
    steps:
      - env:
          OUTPUT1: ${{needs.pre-build.outputs.build_nr}}
          OUTPUT2: ${{needs.pre-build.outputs.env_name}}
        run: echo "$OUTPUT1 $OUTPUT2 $ENVIRONMENT"
      