name: Publish Docker Image Microservices
on:
  push:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ENVIRONMENT: |-
    ${{
       github.ref_name == 'master' && 'production'
    || github.ref_name == 'dev'    && 'dev'
    ||                                'staging'
    }}
jobs:
  pre-build:
    name: Prepare Metadata Pipeline
    runs-on: ubuntu-latest
    outputs:
      build_nr: ${{ steps.build_id.outputs.build_nr }}
    steps:
      - name: Extracts value from the build pipeline
        id: build_id
        run: echo "build_nr=${{github.run_number}}" >> $GITHUB_OUTPUT
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: |-
      ${{
         github.ref_name == 'master' && 'production'
      || github.ref_name == 'dev'    && 'dev'
      ||                                'staging'
      }}
    needs: pre-build
    steps:
      - env:
          OUTPUT1: ${{needs.pre-build.outputs.build_nr}}
        run: echo "$OUTPUT1 $ENVIRONMENT"
      