name: Report Status Pipeline
on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      status:
        required: true
        type: string
      message:
        required: true
        type: string
      badge:
        required: true
        type: string
jobs:
  pre-report:
    name: Prepare Metadata Pipeline
    runs-on: ubuntu-latest
    outputs:
      body: ${{ steps.message_body.outputs.body }}
    steps:
      - name: Message construction ( sample test )
        run: |
          BODY_EXAMPLE="## JaCoCo Test Coverage Summary Statistics"
          echo $BODY_EXAMPLE
      - name: Message construction
        run: |
          BREAKLINE=$'\n'
          NEWLINE=$'\n'
          NEWLINE=$'--------------------------------'
          BODY=$"Report Status: 
            ${{inputs.title}}${BREAKLINE}${NEWLINE}
            ${{inputs.status}}${BREAKLINE}
            ${{inputs.badge}}${BREAKLINE}
            ${{inputs.message}}${BREAKLINE}
            ${{github.run_number}}${BREAKLINE}
            ${{github.sha}}${BREAKLINE}"
          echo $BODY
      - name: Extracts value from the build pipeline
        id: message_body
        run: echo "body=$BODY" >> $GITHUB_OUTPUT
  report:
    name: Status and Report Publication 
    runs-on: ubuntu-latest
    needs: [pre-report]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Commit and push
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git commit -m "${{needs.pre-report.outputs.body}}"
        git push

    - name: Comment on PR
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        gh pr comment ${{github.event.pull_request.number}} -b ${{needs.pre-report.outputs.body}}
      continue-on-error: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}